#!/bin/bash

networkSSID=$(/System/Library/PrivateFrameworks/Apple80211.framework/Versions/Current/Resources/airport -I | grep ' SSID')
networkBSSID=$(/System/Library/PrivateFrameworks/Apple80211.framework/Versions/Current/Resources/airport -I | grep 'BSSID')
signalStrength=$(/System/Library/PrivateFrameworks/Apple80211.framework/Versions/Current/Resources/airport -I | grep 'agrCtlRSSI' | awk '{print $2}')


echo "<result>"
echo "$networkSSID"
echo "$networkBSSID"
echo "RSSI (Signal Strength): $signalStrength"
echo "</result>"