#!/bin/sh
# Geo-IP Location
# Gets an approximation of the computer's current location based on IP

myIP=$(curl -L -s --max-time 10 http://checkip.dyndns.org | egrep -o -m 1 '([[:digit:]]{1,3}\.){3}[[:digit:]]{1,3}')
myLocationInfo=$(curl -L -s --max-time 10 "http://ip-api.com/csv/?fields=continent,country,regionName,city,lat,lon,/$myIP")

if [[ ${#myLocationInfo} -lt 100 ]] ; then
	# An expected result
	echo "<result>$myLocationInfo</result>"
else
	# An unexpected result
	echo "more than 50 characters..."
	echo "<result>Could not determine location</result>"
fi