#!/bin/sh

#Get current signed in user
 currentUser=$(ls -l /dev/console | awk '/ / { print $3 }')

#com.jamf.connect.state.plist location
jamfConnectStateLocation=/Users/$currentUser/Library/Preferences/com.jamf.connect.state.plist

if [ -e $jamfConnectStateLocation ]; then
	
 
 DisplayName=$(/usr/libexec/PlistBuddy -c "Print :DisplayName" $jamfConnectStateLocation || echo "Does not exist")
echo "DisplayName"
echo "<result>$DisplayName</result>"
else
	echo "<result>Not Installed</result>"
fi