#!/bin/sh

#Get current signed in user
 currentUser=$(ls -l /dev/console | awk '/ / { print $3 }')

#com.jamf.connect.state.plist location
 jamfConnectStateLocation=/Users/$currentUser/Library/Preferences/com.jamf.connect.state.plist


if [ -e $jamfConnectStateLocation ]; then
	
 PasswordCurrent=$(/usr/libexec/PlistBuddy -c "Print :PasswordCurrent" $jamfConnectStateLocation || echo "Does not exist")
echo "PasswordCurrent"
echo "<result>$PasswordCurrent</result>"

else
	echo "<result>Not Installed</result>"
fi