#!/bin/bash

# Reports date/time of last password change

# Get currently logged in user

loggedInUser=$( scutil <<< "show State:/Users/ConsoleUser" | awk '/Name :/ && ! /loginwindow/ { print $3 }' )

# Get unix time of last password change
passwordChange=$(sudo dscl . -read /Users/$loggedInUser accountPolicyData |
	tail -n +2 |
	plutil -extract passwordLastSetTime xml1 -o - -- - |
	sed -n "s/<real>\([0-9]*\).*/\1/p")

# Convert epoch time to YYYY-MM-DD hh:mm:ss format
# Convert epoch time to human-readable format
human_readable_time=$(date -r $passwordChange '+%Y-%m-%d %H:%M:%S')

# Print the result
echo "<result>$human_readable_time</result>"