#!/bin/bash

NearestBSSID=$(sudo /System/Library/PrivateFrameworks/Apple80211.framework/Versions/Current/Resources/airport -s | cut -c 34- | grep -v RSSI | awk '{print $1 " " $2}' | sort -nrk2 | head -n 10)

echo "<result>$NearestBSSID</result>"