#!/bin/bash

# Set the Jamf Pro API credentials and server URL
jamfProURL="jamfserver.jamfcloud.com"
jamfusername="your_username"
jamfpassword="yourpassword"

# Set the computer's serial number
COMPUTER_SERIAL="computerSN"

#having to target a specific username makes this where I am not sure how practicle this script is as a "high use script for logging/records"
# Set the username you want to query
targetUsername="username_to_query"

# Request auth token
authToken=$( /usr/bin/curl \
--request POST \
--silent \
--url "$jamfProURL/api/v1/auth/token" \
--user "$jamfusername:$jamfpassword" )

# Parse auth token
token=$( /usr/bin/plutil \
-extract token raw - <<< "$authToken" )

tokenExpiration=$( /usr/bin/plutil \
-extract expires raw - <<< "$authToken" )

localTokenExpirationEpoch=$( TZ=GMT /bin/date -j \
-f "%Y-%m-%dT%T" "$tokenExpiration" \
+"%s" 2> /dev/null )

# Send the API request to get the computer ID
response=$(curl -s -X GET \
  -H "Authorization: Bearer $token" \
  -H "Accept: application/xml" \
  "$jamfProURL/JSSResource/computers/serialnumber/$COMPUTER_SERIAL")

# Extract the computer ID based on the serial number from the response using xmllint and sed
computer_id=$(echo "$response" | xmllint --xpath 'string(/computer/general/id)' - | sed 's/[^0-9]*//g')

# Print the computer ID
echo "Computer ID: $computer_id"

# Send API request to get the computer inventory details
response2=$(curl -s -X GET \
   -H "Authorization: Bearer $token" \
   -H "accept: application/json" \
   "$jamfProURL/api/v1/computers-inventory-detail/$computer_id")

# Extract the management ID from the response using jq
management_id=$(echo "$response2" | jq -r '.general.managementId')

# Print the management ID
echo "Management ID: $management_id"

# Send API request to get the audit information for the specified username
audit_response=$(curl -s -X GET \
   -H "Authorization: Bearer $token" \
   -H "accept: application/json" \
   "$jamfProURL/api/v2/local-admin-password/$management_id/account/$targetUsername/audit")

# Extract the audit information using jq
audit_info=$(echo "$audit_response" | jq '.')

# Display the audit information as a user-visible message using osascript
osascript -e "display dialog \"Audit Information for $targetUsername:\n$audit_info\" buttons {\"OK\"} default button \"OK\""
  
# Expire auth token
/usr/bin/curl \
--header "Authorization: Bearer $token" \
--request POST \
--silent \
--url "$jamfProURL/api/v1/auth/invalidate-token"
