#!/bin/bash

### This is very much a work in progress ###

# Set your Jamf Pro server URL and credentials
JAMF_SERVER="https://server.jamfcloud.com"
API_USER="user"
API_PASSWORD="password"

# Arrays to store site names and their corresponding abbreviations
site_names=("Academic Support" "Athletics" "Cellular Devices" "College of Arts & Sciences" "College of Engineering" "Galveston" "Health" "IT Research" "IT Strategic Alliances & Partnerships" "Labs & Conference Rooms" "Residence Life" "School of Performance, Visualization & Fine Arts" "School of Veterinary Medicine" "Technology Services")
site_abbreviations=("AS - " "ATH - " "CD - " "CAS - " "ENG - " "TAMUG - " "TAMUH - " "ITR - " "ITSAP - " "LCR - " "RL - " "PVFA - " "SVM - " "TS - ")

# Function to get a list of all policies from Jamf Pro
get_all_policies() {
  curl -s -u "$API_USER:$API_PASSWORD" "$JAMF_SERVER/JSSResource/policies"
}

# Function to update the name of a policy
update_policy_name() {
  policy_id="$1"
  new_name="$2"
  curl -s -u "$API_USER:$API_PASSWORD" -X PUT -H "Content-Type: text/xml" -d "<policy><name>$new_name</name></policy>" "$JAMF_SERVER/JSSResource/policies/id/$policy_id"
}

# Get all policies from Jamf Pro
policies=$(get_all_policies)

# Iterate through the policies and update their names
for policy in $policies; do
  current_name=$(echo "$policy" | sed -n -e 's/^.*<name>\(.*\)<\/name>.*$/\1/p')
  new_name=""

  # Check if the policy name contains a site name, and if so, add the abbreviation
  for ((i=0; i<${#site_names[@]}; i++)); do
    site="${site_names[$i]}"
    abbreviation="${site_abbreviations[$i]}"
    if [[ $current_name == *"$site"* ]]; then
      new_name="${abbreviation} - $current_name"
      break
    fi
  done

  # If no site name was found in the policy name, mark it as "Global"
  if [[ -z "$new_name" ]]; then
    new_name="Global - $current_name"
  fi

  # Update the policy name with the new name
  update_policy_name "$(echo "$policy" | sed -n -e 's/^.*<id>\(.*\)<\/id>.*$/\1/p')" "$new_name"
done
